country          = "barbados"
tito_region      = "Barbados"
tito_version     = "pending"
data_version     = "pending"
cpu              = 4096 # AHWA estimate, benchmark first
memory           = 16384
ef5_max_workers  = 4
uses_streamsat   = false
schedule_enabled = false
