country          = "comoros"
tito_region      = "Comoros"
tito_version     = "0c4be51ff6df8e5fb7930ecf685aa6e7cd39290a"
data_version     = "0c4be51ff6df"
cpu              = 4096 # AHWA estimate, benchmark first
memory           = 16384
ef5_max_workers  = 4
uses_streamsat   = true
streamsat_domain = "comoros"
uses_hsaf        = true # HSAF gap-fill
schedule_enabled = false
